version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn -Dmaven.test.skip=true package
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

  checkstyle:
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn checkstyle:check

  test:
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn test

workflows:
  checkstyle-&-tests:
    jobs:
      - build
      - checkstyle:
          requires:
            - build
      - test:
          requires:
            - build
            - checkstyle
